version: "3.8"
services:
  mysqldb:
    image: mysql:latest
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: digitalWallet
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root

