version: "3.8"
services:
  mysqldb:
    image: mysql:latest
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: digitalWallet
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
  springboot-challenge-app:
    image: springboot-challenge-app
    build:
      context: "./"
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "root"
    depends_on:
      - mysqldb
